---
development:
  cloud_name: projetos-consultoria-integrada
  api_key: '977351533993127'
  api_secret: gJYH9SjJoYtaJO69HHIGNofMwXs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: projetos-consultoria-integrada
  api_key: '977351533993127'
  api_secret: gJYH9SjJoYtaJO69HHIGNofMwXs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: projetos-consultoria-integrada
  api_key: '977351533993127'
  api_secret: gJYH9SjJoYtaJO69HHIGNofMwXs
  enhance_image_tag: true
  static_image_support: false